name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create .env file
        run: |
          echo "SUPABASE_URL=https://tgwbdaoptufxxygiyplg.supabase.co" >> .env
          echo "SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnd2JkYW9wdHVmeHh5Z2l5cGxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2MTkyNjYsImV4cCI6MjA5MTE5NTI2Nn0.VqKkta9Zja2w-tEwRUkrhuxOPGPxXM3maAWN8u39bE0" >> .env

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web
        run: |
          flutter build web --base-href /fifa_love_fluter/ --release
          touch build/web/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages
