name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create .env file
        run: |
          echo "SUPABASE_URL=https://xzzsursuurcsrlmjwrwh.supabase.co" >> .env
          echo "SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6enN1cnN1dXJjc3JsbWp3cndoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5NzEwOTUsImV4cCI6MjA4NzU0NzA5NX0.6b8XMyLRaukKu0xO4cNokrwXNw_qGaDwdhLg9ej08DY" >> .env

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --base-href /fifa_love_fluter/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages
